version: 0.2
phases:
  install:
    commands:
      - apt update 
      - apt install openjdk-21-jdk -y
  pre_build:
    commands:
      - mvn clean
  build:
    commands:
      - mvn package
  post_build:
    commands:
      - mvn clean
